### ISSUE TITLE
Verkaufsformular / Gebühren und Spenden Box

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1068]
Deine Gebühren und Spenden Box muss aufgrund von rechtl. Anforderungen umgestaltet werden, Details bitte direkt mit Anna absprechen. Dazu gehört:

- [ ] Netto-Preise nach oben verschieben
- [ ] Quartalsgebühr prominenter platzieren
- [x] AGB + Widerruf abhacken lassen
- [x] gesamt in gesamtpreis umbenennen

**Comment by annakress** [comment]
hmm, ist hier noch was pending für mich?

**Comment by chiramiso** [comment]
Nein
