### ISSUE TITLE
Umbenennung eG

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1119]
sobald die eG umbenannt ist, müssen wieder texte usw. angepasst werden, siehe checkliste umbenennng

Umbenennung CSV Doku AGB Datenschutz #1117

**Comment by chiramiso** [comment]
Codeseitig ist alles auf Fairmondo umgestellt und auch schon auf Production, wenn noch iwelche Texte, wie AGBen oder so umgestellt werden müssen, bitte jetzt.

**Comment by chiramiso** [comment]
So, ich hab mal die CMS Texte für FAQ, AGB und Datenschutz angepasst.
Wie sieht das mit den PDFs auf dem Marktplatz aus? Sind die schon geändert?

**Comment by annakress** [comment]
bin dran.

**Comment by annakress** [comment]
pdfs datenschutz + agb an interne mailingliste geschickt.

**Comment by chiramiso** [comment]
ist online.
