### ISSUE TITLE
Affiliate Network

### ISSUE THREAD

**Issue by andreasknoepfle** [fairmondo/fairmondo#1161]
belboon.com ,siehe mail von richard, dort ist auch doku angehängt

**Comment by annakress** [comment]
update: ich habe zwischen den jahren vertragsunterlagen dort eingereicht, wir warten weiter auf freischaltung.

**Comment by annakress** [comment]
freischaltung erfolgt, ich habe konstantin die zugangsdaten geschickt.

**Comment by andreasknoepfle** [comment]
projektleitung: anna

**Comment by annakress** [comment]
juchhu, ich habe die anzahlung vorgenommen und um freischaltung gebeten! ein erstes test-affiliate-programm habe ich auch schon angelegt, allerdings muss das eben freigeschaltet werden. nun ist aus meiner sicht folgendes zu tun:

schritt1: die zugangsdaten bekommt ihr von mir. (ich lege auch gerne einen test-werbenden-account an, allerdings kann ich das erst, wenn das programm freigeschaltet ist.)
mit den angelegten 2 werbematerialien (beziehen sich zur zeit alles auf bücher, einmal ein logo, einmal ein text) sollte das tracking des sales getestet werden. eine provision gibt es nur bei einem sale. anleitung zum testen gibt es im handbuch, das schick ich an die mailingliste.
Hier wäre noch eine offene frage: wie können wir einschränken, bei welchen artikeln die provision gezahlt wird? z.b. nur bücher vom ecobookstore, keine artikel von privatverkäufern, keine fairen artikel mit nur 3% verkaufsprovision. (bei denen müsste ich die konditionen, was wir den werbenden zahlen, jeweils anpassen, damit wir kein minus machen.) eventuell können wir das nur machen, wenn wir nur csv-dateien anbieten, siehe schritt 2. 

schritt 2: ich würde gerne als weiteres werbemittel alle artikel vom ecobookstore als csv-datei bei belboon hinterlegen. anleitung und csv-format von belboon sind in deren handbuch, schick ich euch gleich an die mailingliste.  wir müssten also unser format konvertieren und regelmäßig auf unserem server aktuell bereithalten. das könnte bei dem datenbestand von ecobookstore eine herausforderung sein. eventuell können wir ihn bitten, uns die datei an das csv-format von belboon anzupassen. oder wir müssen uns auf eine teilmenge seiner artikel beschränken. wäre natürlich schade.

**Comment by chiramiso** [comment]
Erster Schritt, done, für den CSV-Exportteil gibt es ein eigenes Issue (#1378)
