### ISSUE TITLE
Titelbild von Artikeln

### ISSUE THREAD

**Issue by Merlind** [fairmondo/fairmondo#1184]
Hi, die Ansicht der Titelbilder ist bei manchen Händlern unterschiedlich in der Gesamtansicht und dem einzelnen Artikel - siehe Beispiel.
Bei einigen Artikeln ist das ein Problem, weil sie überhaupt nicht das Produkt zeigen.

https://www.fairmondo.de/articles/noggad-very-valuable-time--4
https://www.fairmondo.de/users/noggad

![bildschirmfoto 2014-11-21 um 15 22 21](https://cloud.githubusercontent.com/assets/7868669/5143642/86d09e0c-7192-11e4-8bfc-5c3924c16adc.png)
![bildschirmfoto 2014-11-21 um 15 22 12](https://cloud.githubusercontent.com/assets/7868669/5143643/86dd1c04-7192-11e4-9e32-5b8e5868641e.png)

**Comment by andreasknoepfle** [comment]
beispiel stimmt wieder ... vlt ein indexing fehler ? 
reopen wenn es ein anderes beispiel gibt bitte
