### ISSUE TITLE
Geschenkgutscheine

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1200]

**Comment by chiramiso** [comment]
Es sollen keine Gebühren auf mit Gutscheinen bezahlte Bücher anfallen

**Comment by annakress** [comment]
eine kundin berichtet gerade, dass sie keinen code eingeben kann: https://forum.fairmondo.de/t/gutschein-von-ecobookstore-einlosen/551/4

stimmt, ich sehe auch kein feld mehr dafür. bitte beheben.

**Comment by KonstantinKo** [comment]
Ist kein Fehler sondern Verhalten entsprechend der Anforderungen. Die Gutscheineingabe gehört zur Bezahlabwicklung und nicht zur Kaufabwicklung. Man kauft also zuerst den Artikel und danach gibt man erst den Gutscheincode ein.

**Comment by annakress** [comment]
ah, stimmt. danke.

**Comment by annakress** [comment]
Nachtrag: Dann machen wir es aber ein bisschen klarer für den Kunden mit Texten:

Auf der Seite 3. Schritt im Warenkorb macht der Text für mich keinen Sinn: "Gesamter Gutscheinbetrag", wo eigentlich der Gesamtpreis steht (da ist ja noch gar nicht klar, wie hoch der Gutscheinbetrag ist, also Höhe des Gutscheins...) -> Sollte Gesamtbetrag oder so ähnlich sein? Wie beim Kauf ohne Gutschein. Bitte korrigieren.

Bei Gesamtbetrag könnte man dann ein dickes Sternchen mit Erklärung anfügen, also z.B. 20,90 €*

Und unter dem Kasten mit der Übersicht des Gesamtpreises einen Text: "* Wenn Du auf Zahlungspflichtig bestellen klickst, kannst Du anschließend Deinen Gutscheincode eingeben. Sollte der Gutschein für Deinen Kauf nicht ausreichen, wird Dir der Restbetrag zur Überweisung an den Händler angezeigt. Übersteigt der Wert des Gutscheins den Gesamtbetrag Deines Kaufs, wird der verbleibende Betrag gespendet. Weitere Konditionen entnimm bitte Deinem Gutschein."

**Comment by annakress** [comment]
marc ist zwar eingetragen, aber er noch nicht dazu gekommen ist, bitte an paul freigeben.
