### ISSUE TITLE
Vertikale Kategorien-Navileiste spinnt

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1205]
klick ich in der horizontalen kategorienleiste z.b. auf medien, ohne einen suchbegriff einzugeben, sehe ich in der kategorienbox links falsche anzahlen für alle artikel (also viel zu kleine zahlen), die nicht in medien sind, z.b.:

 Alle Kategorien
Medien (12386)
Filme (5784)
Games (257)
Musik (6163)
Serien (8)
Bücher (8623)
Dienstleistungen (1)
Elektronik (7)
Freizeit & Sport (4)
Kinder & Baby (9)
Kunst & Sammeln (80)
Wohnen & Leben (2)
Weitere (23)

Klicke ich dann z.B. auf Dienstleistungen, wird die Zahl für Dienstleistungen korrekt, dafür verschwinden die meisten Kategorien, aber nicht alle (ich sehe alle Unterkat. von Dienstleistungen und dann aus irgendeinem Grund nur die Oberkategorien Freizeit & Sport (2) und Medien (1)):

 Alle Kategorien
Dienstleistungen (23)
Beratung & Coaching (16)
Gastronomie & Events (2)
Gebäudedienstleistungen (1)
Handwerkerdienstleistungen (2)
Marketing (1)
Schulungen & Seminare (7)
Freizeit & Sport (2)
Medien (1)

**Comment by annakress** [comment]
die probleme mit den falschen anzeigen in der vertikalen kategorieleiste wurden zwar gelöst, aber dafür vermutlich ein anderes problem eingeführt:

suche ich z.b. nach "socken", wird die leiste nicht mehr an die anzahl der suchergebnisse pro kategorie angepasst, sondern zeigt weiterhin die anzahlen aller artikel auf dem marktplatz, also nicht nur für socken. deshalb kann ich mich für das suchergebnis nicht mehr durch die kategorien durchklicken.

**Comment by chiramiso** [comment]
Geht wieder.

**Comment by chiramiso** [comment]
Muss erweitert werden um auch Filter als Einschränkung zu akzeptieren

**Comment by annakress** [comment]
leider tritt das problem wieder auf. klicke ich auf lebensmittel in der horizontalen leiste, verschwindet in der vertikalen leiste z.b. dienstleistungen, zudem sind die anzahlen in den anderen kategorien fehlerhaft.

**Comment by andreasknoepfle** [comment]
die sibling kategorien werden nun immer eingeblendet und ohne anzahl ... müsste dann auch jetzt stimmen
