### ISSUE TITLE
Artikel kann, nach aktualisieren von Ecobookstore, nicht mehr gefunden werden

### ISSUE THREAD

**Issue by Merlind** [fairmondo/fairmondo#1225]
wenn ich nach "boyhood" suche, dann findet er nicht die DVD, die in folgender Sammlung ist 
https://www.fairmondo.de/libraries/8052
Diesen Artikel habe ich sonst immer über die Suche gefunden, gestern war er nicht mehr da, da Ecobookstore seine Artikel aktualisiert hat. Jetzt kann ich ihn nicht mehr über die Suche finden, auch nicht mit EAN Nr oder so.

Boyhood DVD https://www.fairmondo.de/articles/boyhood-video-dvd-ean-5053083010089
(nicht die Blue Ray Version)
![bildschirmfoto 2014-12-11 um 10 26 14](https://cloud.githubusercontent.com/assets/7868669/5391920/f5262a50-8120-11e4-87a4-dcffc6ece745.png)

**Comment by andreasknoepfle** [comment]
das dauert immer kurz bis der wieder gefunden wird
