### ISSUE TITLE
Artikel hat kein Kauf- und Sammelbutton

### ISSUE THREAD

**Issue by Merlind** [fairmondo/fairmondo#1233]
![bildschirmfoto 2014-12-15 um 15 15 04](https://cloud.githubusercontent.com/assets/7868669/5437041/2d499b70-846d-11e4-8390-92a52d62d110.png)

https://www.fairmondo.de/articles/unterwasserwelt--2909252

**Comment by chiramiso** [comment]
#1188 same same
