### ISSUE TITLE
Artikelerstellung + Suche: Kleidergrößen und ISBN

### ISSUE THREAD

**Issue by GREENnow** [fairmondo/fairmondo#1236]
Es wäre schön, wenn bei der Artikelerstellung bei Kleidung und Büchern zusätzliche Felder implementiert würden, mit denen eine bessere Artikelsuche auf dem Marktplatz ermöglicht wird.

Möchte ich bspw. ein Buch online stellen, erscheint zusätzlich ein Feld, in das die ISBN-Nummer eingetragen wird, damit Nutzer_innen einfach nach dieser suchen können.

Bei Kleidung könnte ein zusätzliches Feld für die Größe erscheinen (bei gebrauchten Waren). Bei Neuware könnte eine Auswahlbox implementiert werden, mit der der_die Verkäufer_in angeben kann, wie oft der Artikel in welcher Größe erhältlich ist. Somit könnte beim Kauf auch direkt die Größe gewählt werden und müsste nicht mehr extra abgefragt werden mit der Gefahr, dass der Artikel in der gewünschten Größe gar nicht mehr erhältlich ist.

Die Kleidungsgröße könnte dann auch als Filter auf dem Marktplatz integriert werden.

**Comment by andreasknoepfle** [comment]
duplicate of #807
