### ISSUE TITLE
Nutzer kann nicht auf Warenkorb zugreifen

### ISSUE THREAD

**Issue by marcaltmann** [fairmondo/fairmondo#1237]
Der Nutzer "Madais" (mdanieli@danielihof.de) hat berichtet, dass er nicht auf seinen Warenkorb zugreifen kann:
"... ich versuche gerade mit meinem privaten Profil (Madais, mdanieli@danielihof.de) auf Fairmondo einzukaufen… Sobald ich auf den Warenkorb zugreifen möchte, erhalte ich entweder den Fehler Entschuldigung, da ist wohl etwas schiefgelaufen. Die Seite die du aufrufen wolltest funktioniert nicht richtig. oder den Fehler Serverfehler - 500 Entschuldigung, da ist wohl etwas schiefgelaufen."

**Comment by andreasknoepfle** [comment]
we have a stacktrace:
Module::DelegationError (LineItem#article_price delegated to article.price, but article is nil: #<LineItem id: 6044, line_item_group_id: 5356, article_id: 6565330, requested_quantity: 1, created_at: "2014-12-10 15:02:12", updated_at: "2014-12-10 15:02:12">):
  app/models/line_item.rb:7:in `rescue in article_price'
  app/models/line_item.rb:7:in `article_price'
  app/objects/abaci/cart_abacus.rb:31:in `calculate_line_item'
  app/objects/abaci/cart_abacus.rb:23:in `block in calculate_group'
  app/objects/abaci/cart_abacus.rb:23:in `calculate_group'
  app/objects/abaci/cart_abacus.rb:17:in `block in calculate_total'
  app/objects/abaci/cart_abacus.rb:16:in `calculate_total'
  app/objects/abaci/cart_abacus.rb:9:in `initialize'
  app/controllers/carts_controller.rb:19:in `new'
  app/controllers/carts_controller.rb:19:in `show’

**Comment by andreasknoepfle** [comment]
3ec9b90d268f487788cdd4c1c9120b16ac0e99ec
