### ISSUE TITLE
Startseitenänderungen + Sammlungen nach Weihnachten (Textänderungen)

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1240]
Ziel ist, die beiden Schlagworte Geschenke und Weihnachten zwischen Weihnachten und Neujahr vom Marktplatz zu nehmen, also logischerweise nciht jetzt sofort:

1)    Billboards: Geschenke für Kinder ganz raus + Geschenke unter 15 Euro in "Produkte unter 15 Euro" umändern + Ecobookstore: „Weihnachten“ im Billbaord bei den Gutscheinen streichen, ansonsten Billboard beibehalten.
   
2) GESCHENK-EMPFEHLUNGEN VON NUTZER*INNEN umbenennen nach „Empfehlungen ...“, auch den Link unten „Mehr Geschenk-Empfehlungen“ : „Geschenk“ rausnehmen

  3)  https://www.fairmondo.de/libraries: Text ändern: Hier findest Du Empfehlungen von anderen Nutzer*innen für schöne Artikel. Du kannst auch selbst Sammlungen anlegen – lies hier, wie das geht.

 4)   https://www.fairmondo.de/geschenk-sammlungen → Seite anpassen, alles mit Tag #Geschenke rausnehmen (macht Anna)

**Comment by chiramiso** [comment]
Done
