### ISSUE TITLE
Suche findet keine Ergebnisse

### ISSUE THREAD

**Issue by Chimperoni** [fairmondo/fairmondo#1243]
Suche nach Buchtitel "er ist wieder da" bringt kein Ergebnis. Suche nach dem Autor "Timur Vermes" bringt das gewünschte Ergebnis. https://forum.fairmondo.de/t/suhe-nach-buchtitel-funktioniert-nicht/457

**Comment by andreasknoepfle** [comment]
https://www.fairmondo.de/articles?article_search_form[q]=Timur%20Vermes
