### ISSUE TITLE
Anfragen anderer Nutzer / Emailtext ergänzen

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1246]
Wenn ein Nutzer mir eine Anfrage wegen eines Artikels zusendet, erhalte ich eine Nachricht mit dem Button "Anfrage beantworten". Wenn ich darauf klicke, wird die Emailadresse des Nutzers in eine neue Nachricht übernommen. Sehr sehr praktisch wäre es, wenn auch der Betreff und die Nachricht des Nutzers in die Email übernommen werden, so dass ich sie nicht rüberkopieren muss.

Schön wäre auch eine Textänderung in der Mail. Statt: "Ein*e Fairmondo-Nutzer*in hat dir eine Rückfrage zu deinem Artikel "2 Paar Ohrstecker" gesandt:" Besser: "[Nutzername mit Link zum Profil] hat dir eine Rückfrage zu deinem Artikel "2 Paar Ohrstecker" gesandt:"

Auch wäre es besser, die Emailadresse nicht hinter dem Button-Klick zu verstecken, sondern zusätzlich anzuzeigen. Z.B. unter dem Button: "Email-Adresse von [Nutzername]: [Emailadresse]"
Hier wäre eventuell darauf zu schauen, wie die Text/Non-HTML-Version der Mail aussieht, damit da kein Text wiederholt wird.

Und noch eine Kleinigkeit: Hallo Anna, -> Der Anredetext in der Email sollte die gleiche Schriftgröße wie der Rest der Nachricht haben, im Moment ist er größer. Ist unnötig.

**Comment by chiramiso** [comment]
Done
