### ISSUE TITLE
Navileiste Optimierung

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1247]
Die obere Navileiste mit Verkaufen, Sammlungen, Anmelden usw:

Die Menüs werden derzeit per Mausklick ausgeklappt, besser wäre Mausover, gerade wenn Nutzer suchen, wo sie sich registrieren können, wäre das schneller zu finden.

**Comment by chiramiso** [comment]
Dabei dann unbedingt an Touch-Geräte denken!

**Comment by annakress** [comment]
kann man bei touch beim klick verbleiben und bei nicht-touch beim mouse-over?

**Comment by marcaltmann** [comment]
Ich musste leider feststellen, dass mein bisheriger Ansatz nicht optimal war: Ich hatte JS-active-toggle um Hover-Events (mouseenter, mouseleave) erweitert, in der Annahme, dass diese auf Touch-Geräten nicht getriggert werden. Werden sie aber doch, dadurch werden auf Touch-Geräten mehrere Events bearbeitet (mouseenter, click), was es etwas kompliziert macht.
Ich würde daher jetzt einen anderen Ansatz verfolgen: JS-active-toggle für die Klick-Dropdowns vorbehalten und dann ein CSS-Modul für Hover-Dropdowns schreiben, das ähnlich wie die Dropdowns in der Kategorienleiste funktioniert. Das können wir dann für die Navileiste, die Kategorienleiste und die Filter verwenden.
