### ISSUE TITLE
Kombiversand auch für Privatverkäufer freischalten

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1249]

**Comment by annakress** [comment]
Da der Kombiversand für Händler gut läuft, soll er nun auch für Privatverkäufer nutzbar sein. Als Teil der Strategie, mehr Privatverkäufer auf die Plattform zu holen.

**Comment by chiramiso** [comment]
Done

**Comment by annakress** [comment]
ich hab grade gesehen, dass Kostenfreier Versand nicht eingeschaltet wurde für Privatverkäufer. Soll aber auch eingeschaltet werden.

**Comment by chiramiso** [comment]
Done
