### ISSUE TITLE
warenkorb auch mit 0 artikeln anzeigen, nicht erst wenn man kauft

### ISSUE THREAD

**Issue by chiramiso** [fairmondo/fairmondo#1257]
references #1248

warenkorb auch mit 0 artikeln anzeigen, nicht erst wenn man kauft

**Comment by KonstantinKo** [comment]
Review: Warum die extra action? Hätte man nicht einfach einen leeren cart generieren können und den anzeigen? So gibt es auch den Unterschied, dass bei empty_cart nicht die Titelleiste mit den 3 Bezahlschritten angezeigt wird, bei einem tatsächlichen leeren Cart aber schon.
Neben dieser eventuellen Grundsatzdiskussion sieht der Code soweit gut und kann von mir aus merged werden.
