### ISSUE TITLE
Zur Kasse umbenennen

### ISSUE THREAD

**Issue by chiramiso** [fairmondo/fairmondo#1264]
references #1248

Zur Kasse umbenennen und eventuell A/B testen (habe dazu Optimizely ausprobiert, allerdings gibt es da Probleme mit Sessionbasierten Seiten wie dem Warenkorb....) -> "Zur Kasse (über den Sicherheitsserver)" -> soll mehr Vertrauen wecken, wir sind ja auch SSL-Verschlüsselt

**Comment by chiramiso** [comment]
Hab den Button String jetzt geändert, sollen wir das noch A/B testen?

**Comment by annakress** [comment]
man kann unsere warenkorb seiten leider nicht optimizely-testen, also bitte so deployen.

**Comment by chiramiso** [comment]
Done
