### ISSUE TITLE
E-Mail zur Erinnerung bei nicht gekauften Warenkörben

### ISSUE THREAD

**Issue by chiramiso** [fairmondo/fairmondo#1266]
references #1248

idee 4: sich den warenkorb per email als Erinnerung zuschicken lassen (Tipp aus einem Best Practice Portal):
"Warenkorbinhalt an Deine Emailadresse senden" mit pop-up zur
Emaileingabe und Info, dass die Email nicht weiter gespeichert wird.
Und Hinweis, dass Registrierung den Vorteil hat, dass der Korb
gespeichert wird mit Link zur Registrierung.

**Comment by chiramiso** [comment]
#1248

**Comment by chiramiso** [comment]
Ich davon aus, dass der zugeschickte Link zum Warenkorb mit allen Browser dann funktionieren soll? nicht nur mit dem, in dem der Warenkorb erstellt wurde?

**Comment by annakress** [comment]
mir ging es um eine einfachste lösung, also nicht an anderen browsern. einfach eine nette zusammenstellung der produkte, mit einem link unten zum marktplatz / registrieren. für eine genaue spec habe ich gerade keine zeit, also entweder selber nett machen, oder zurückstellen erstmal.

**Comment by chiramiso** [comment]
Wartet auf Texte

**Comment by annakress** [comment]
****
Im Warenkorb statt „Den Inhalt des Warenkorbes per E-Mail versenden“ besser:
"Die Artikel als Merkliste per Email versenden“ (damit der Nutzer den Zweck versteht)
Den Text bitte oben rechts statt links platzieren, soll aus der Aufmerksamkeitsachse raus, damit es nicht vom Kauf ablenkt.

***
Popup Textkorrekturen: 
Warenkorb per E-Mail versenden ändern in → Als Merkliste per Email versenden

Text:
Hier kannst Du Dir den Inhalt Deines Warenkorbs per Email zuschicken lassen, falls Du Dich noch nicht registrieren möchtest. Wir speichern Deine Emailadresse nicht. (vielelicht in fett setzen)

Wenn Du Dich auf Fairmondo kostenfrei registrierst, kannst Du Deine Merklisten bequem auf Fairmondo verwalten.

****
Email:
Betreff: Deine vorgemerkten Artikel auf Fairmondo
Inhalt Titel: Deine vorgemerkten Artikel auf Fairmondo 
Inhalt Text: Du hast Dir folgende Artikel auf Fairmondo vorgemerkt:

Nach der Auflistung der Artikel zu den 2 Buttons:
1. Button: Wäre es möglich, einen „Artikel kaufen“ Button zu machen, der auf Klick die Artikel in den Warenkorb legt? Also statt des Zu Fairmondo Buttons?
Falls nicht, sollten wir die 2 Buttons wie gehabt behalten, aber mit Piwik-Kampagnen versehen:
Zu Fairmondo: https://www.fairmondo.de/?pk_campaign=email-merkliste
Jetzt registrieren: https://www.fairmondo.de/user/sign_up?pk_campaign=email-merkliste
Darunter noch den Text: 

Kostenfrei registrieren und Merklisten direkt auf Fairmondo verwalten.

Das macht uns anders:
- Die schönsten und fairsten Produkte im Netz ent­decken
- Keine Einstell­gebühren und nur 6% Verkaufs­provision (3% für faire Artikel)
- Ein faires Unternehmen dahinter

**Comment by chiramiso** [comment]
Danke, wird gemacht.

Artikel auf Klick in den Warenkorb legen wird nicht so einfach, deshalb hatte ich ja schon weiter oben nachgefragt, wie das aussehen soll, und ob das dann in allen Browsern funktionieren soll. Bräuchte auf jeden Fall etwas Nacharbeit.

**Comment by KonstantinKo** [comment]
Review:
Zwei Anmerkungen. Zum einen könnte man argumentieren, dass es mehr RESTful wäre, das als Merkliste#create zu definieren als als extra cart action - es lohnt sich aber denk ich nicht das noch umzustellen, da ja auch keine records erstellt werden.

Zum anderen macht der Text "Wenn Du Dich auf Fairmondo kostenfrei registrierst, kannst Du Deine Merklisten bequem auf Fairmondo verwalten." keinen Sinn, wenn man bereits eingeloggt ist. Ich bin ja schon eingelogt. Kann ich dann nicht auch meine Merkliste gleich irgendwie verwalten? Wenn ja wie? (Oder reden wir dabei von Sammlungen?)
Müssen wir da überhaupt nach ner EMail fragen? Wir haben doch die vom Nutzer.

**Comment by chiramiso** [comment]
Erstmal erledigt. Konstantins Anmerkungen müssen wir wohl nochmal überdenken.
