### ISSUE TITLE
Suche zeigt Artikel an die dann nicht gefunden werden

### ISSUE THREAD

**Issue by Merlind** [fairmondo/fairmondo#1268]
wenn ich einfach in der Kategorie Bücher suche, ohne Suchbegriff, dann wird mir im Menü links angezeigt, dass es z.B. 2 Graphik Novels gibt, aber wenn ich da draufklicke, wird Nichts gefunden.

![bildschirmfoto 2015-01-14 um 21 39 06](https://cloud.githubusercontent.com/assets/7868669/5747157/395cdf04-9c36-11e4-9492-fc042e355a24.png)

**Comment by chiramiso** [comment]
Besteht das Problem noch? Ich kann es nicht reproduzieren.

**Comment by chiramiso** [comment]
Geschlossen, weil lässt sich nicht reproduzieren
