### ISSUE TITLE
Betrugsvorfälle Ausweis unterbinden

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1269]
In den Kaufemails und im Warenkorb blenden wir eventuell an verschiedenen Stellen den Text ein, dass man, um sich gegen Betrugsvorfälle zu schützen, u.a. den Perso zuschicken lassen sollte (oder die Daten des Händlers, was nach Perso klingt). Ich habe den Text allerdings auf der Plattform nicht gefunden, bin also nicht sicher, ob das noch stimmt. Bitte die Texte nach "Sicherheitshinweis" bzw. "Personalausweis" durchsuchen. Falls ein solcher Text für Käufer auftaucht, auf folgende (oder verkürzte, je nachdem) Version umwandeln. Bei Zweifeln bei mir nachfragen:

Sicherheitshinweis: Der Kaufvertrag kommt zwischen Dir und dem Anbieter zustande. Fairmondo ist bekanntlich nur Plattformbetreiberin. Um dich als Käufer*in gegen Betrugsfälle zu schützen, empfiehlt Fairmondo – inbesondere bei Artikeln und Käufen ab 100 Euro - eine sichere Bezahlmethode wie PayPal (da PayPal einen Käuferschutz beinhaltet) oder Barzahlung bei Abholung. In Einzelfällen kann es bspw. Auch sinnvoll sein, Dir die Eigentümerstellung bzw. Nachweise der Echtheit (z.B. Software) oder Unversehrtheit (durch Fotos bei Gebrauchtartikeln) nachweisen zu lassen.

**Comment by chiramiso** [comment]
Done
