### ISSUE TITLE
Erneutes Problem: Bereits verkaufte Artikel werden über Profil und Suche gefunden

### ISSUE THREAD

**Issue by Chimperoni** [fairmondo/fairmondo#1271]
Ist bereits closed, Problem ist aber immer noch oder wieder aktuell:
https://github.com/fairmondo/fairmondo/issues/1242

Artikel als Beispiel: https://www.fairmondo.de/articles/stickset-winnie-pooh

**Comment by chiramiso** [comment]
#1272 beschreibt das gleich Problem

**Comment by annakress** [comment]
passiert mir auch relativ oft, dass ich auf solche artikel stoße. ist weider ein größeres problem? zeitabschätzung?

**Comment by chiramiso** [comment]
Eventuell sind die Slugs zweimal vorhanden, d.h. wir müssen eigentlich die DB aufräumen.
Letzte ID finden, alle Artikel neu indizieren (über Zahlen, mit Jobs)

**Comment by HDValentin** [comment]
Kann das Problem bestätigen. Habe aktuell im Bereich meiner Postleitzahl gesucht und bekam meine verkauften Artikel angezeigt.

**Comment by chiramiso** [comment]
ich habe mal alle Artikel neu indiziert. tritt das problem noch auf?

**Comment by HDValentin** [comment]
Ja, hat funktioniert. Abgelaufene Anzeigen sind raus.
