### ISSUE TITLE
Benutzerunfreundliches Verhalten der Suchalgorithmen

### ISSUE THREAD

**Issue by GREENnow** [fairmondo/fairmondo#1272]
Ich habe in den letzten Wochen mehrmals nach einem Artikel gesucht, wie im beigefügten Screenshot zu sehen ist.

Der Artikel wird gefunden, klicke ich darauf, wird angezeigt, dass er nicht mehr verfügbar sei, aber auf einen ähnlichen Artikel im Angebot verwiesen, bei dem es sich der Beschreibung nach um den gesuchten Artikel handeln müsste. Möchte ich diesen Link anklicken, passiert gar nichts.

Für Nutzer_innen ist dieses Suchverhalten bestimmt alles andere als intuitiv und führt in einigen Fällen bestimmt dazu, den Kauf auf der Plattform wegen benutzerunfreundlicher Bedienung nicht zu tätigen.

**Comment by GREENnow** [comment]
https://www.fairmondo.de/articles/die-werwolfe-von-dusterwalt-der-pakt-spiel-ean-3558380023616

**Comment by chiramiso** [comment]
Das alte Problem mit geschlossenen aber trotzdem indizierten Artikeln
