### ISSUE TITLE
Forumslink anpassen, ist veraltet

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1273]
ich wollte vorhin von der Startseite ins Forum wechseln und habe es jeweils über die
Buttons „Hilfe“ und „Feedback“ probiert. Auf beiden nachfolgenden Seiten scheint das Forum
zwar verlinkt zu sein, aber falsch, nämlich noch unter der alten Adresse
https://info.fairmondo.de/infoblog/forum/. Dazu erscheint immerhin ein Hinweis „Das
Fairmondo-Forum zieht um“ und die neue Adresse, aber wieso wird nicht direkt die neue
Adresse zum Forum verlinkt?

Anm. Anna: neue Adresse: https://forum.fairmondo.de/
Bitte schauen, ob die noch wo anders als Hilfe/Feedback verlinkt ist und anpassen. DAnke!

**Comment by chiramiso** [comment]
Done. Dieser Link lässt sich übrigens von Admins auf https://www.fairmondo.de/contents/faq-teaser/edit bearbeiten. Ist nichts was irgendwo hardgecoded ist :)
