### ISSUE TITLE
Spendenberechnung fehlerhaft bei mehreren Artikeln

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1274]
wie mir gerade auffällt, wird mir in Transaktion 5835
(https://www.fairmondo.de/line_item_groups/5835?tab=payments) das zu spendende 1% an
INKOTA falsch berechnet. Es werden 0,48€ angezeigt, da der Kunde aber gleich 2 Exemplare
gekauft hat, müssten es 0,96€ sein.

**Comment by chiramiso** [comment]
Darf ich mir leider nicht angucken unter dem Link, aber ich schau mal woran das liegen könnte

**Comment by annakress** [comment]
gemeldet von kiwigarten, hab das ticket schon geschlossen.

**Comment by chiramiso** [comment]
Fixed it!
