### ISSUE TITLE
Shopübersicht zeigt Artikel, der in meinem Profil nicht eingestellt ist

### ISSUE THREAD

**Issue by Merlind** [fairmondo/fairmondo#1275]
Im Fairmondoshop (bestellungen@fairmondo.de) ist ein Testartikel angezeigt, der aber in meinem Profil unter eingestellten Artikeln nicht zu finden ist…
Siehe Grafiken
![bildschirmfoto 2015-01-19 um 18 52 13](https://cloud.githubusercontent.com/assets/7868669/5805124/8eab2720-a00c-11e4-82cd-148fc30a843d.png)
![bildschirmfoto 2015-01-19 um 18 51 40](https://cloud.githubusercontent.com/assets/7868669/5805127/92ccd286-a00c-11e4-99d6-7885181003bd.png)

**Comment by chiramiso** [comment]
#1271 vermutlich das selbe Problem
