### ISSUE TITLE
Keine Gebühren für Privatverkäufer

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1280]
Für Privatverkäufer werden voraussichtlich in Zukunft keine Verkaufsgebühren mehr erhoben. Wir bereiten bereits technisch vor. Die Änderungen betreffen nur Privatprofile:

Verkaufsformular:
- Die obere Zeile "Bitte beachte, dass bei erfolgreichem Verkauf eine Gebühr gemäß unserer Gebührenordnung anfällt. Die Zahlung erfolgt per Rechnung." wird nur für Privatverkäufer ersetzt durch: "Keine Einstellgebühr, keine Verkaufsgebühr für Dich als Privatverkäufer*in - alles komplett kostenfrei"

- Wenn man auf Vorschau klickt, müsste auf der nächsten Seite die komplette Box mit den Gebühren verschwinden, nur der Button bleibt: "Kostenfrei verkaufen". AGB etc. nicht nötig, da kostenfreie Leistung.

- Bei freiwilliger Spende: Text über dem Button "Kostenfrei verkaufen": "Du vepflichtest Dich, bei erfolgreichem Verkauf X Euro zu spenden."

Bei den Artikelanzeigen: bei Privatverkäufen müsste der Satz weg "Das faire Prozent 
1% werden von uns an Transparency International gespendet"

- Fastbill -> nicht mehr nötig, Verkaufsdaten dorthin zu versenden. 

- Einstell-email: 
- Text kann raus "Bei erfolgreichem Verkauf fallen folgende Gebühren an (inkl. 19% MwSt.): ...."
- Der Hinweis auf die freiwillige Spende sollte aber wie beim Einstellen, siehe oben, erscheinen.
- Zudem wird Widerrufstext nicht mehr benötigt (da kostenfreie Dienstleistung), kann komplett raus.

-Bisher musste man glaube ich vor dem ersten Verkauf seine Bankdaten für Rechnungen zwangsweise ergänzen. Dies sollte für Privatverkäufer entfallen.

- Was ist wenn als Privatverkäufer kosten los eingestellt, und später Profil auf gewerblich genädnert?

**Comment by chiramiso** [comment]
Werde ich mich ab Montag drum kümmern. Sollte kein Problem sein, das innerhalb einer Woche umzusetzen. (Hoffe ich)

Ich werde auch nochmal darüber nachdenken was sonst noch alles betroffen sein könnte...

**Comment by annakress** [comment]
wäre super, wenn auch konstantin unterstützt, falls das sinnvoll ist.

**Comment by KonstantinKo** [comment]
Ist in Absprache mit Paul erstmal nicht sinnvoll, sollte bis Ende der Woche auch so fertig sein

**Comment by annakress** [comment]
Also diese Änderung ist auf Staging nicht vorhanden, wäre aber wichtig für einen einfacheren Verkauf. Also wenn ich zum ertsen Mal auf Verkaufen klicke, werde ich auf das Profil umgeleitet. Meine Adresse zu ergänzen ist OK, aber Bankdaten braucht man nicht.

-Bisher musste man glaube ich vor dem ersten Verkauf seine Bankdaten für Rechnungen zwangsweise ergänzen. Dies sollte für Privatverkäufer entfallen.

**Comment by annakress** [comment]
Auch kann im Profil das Häckchen raus:

Ich ermächtige die Fairmondo eG widerruflich, die fälligen Verkaufsgebühren im Einzugsermächtigungsverfahren einzuziehen.*

**Comment by annakress** [comment]
Und dieser Satz wurde nicth geändert:

Die obere Zeile "Bitte beachte, dass bei erfolgreichem Verkauf eine Gebühr gemäß unserer Gebührenordnung anfällt. Die Zahlung erfolgt per Rechnung." wird nur für Privatverkäufer ersetzt durch: "Keine Einstellgebühr, keine Verkaufsgebühr für Dich als Privatverkäufer*in - alles komplett kostenfrei"

**Comment by annakress** [comment]
Wurde denn auch dieses Popup berücksichtigt? Es kommt, wenn ich auf Artikelvorschau gehe, und dann die Seite verlassen will, ohne das Angebot einzustellen. Da muss natürlich ein anderer Text als gebührenpflichtig rein.

Achtung, Du hast Deinen Artikel noch nicht eingestellt. Um das zu tun, klicke auf "Angebot gebührenpflichtig einstellen". 

Möchtest du wirklich die Seite verlassen?

**Comment by chiramiso** [comment]
Sollte jetzt soweit alles behoben sein
