### ISSUE TITLE
Profilbild verkleinern

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1281]
Unter https://www.fairmondo.de/user/edit wird mein Profilbild riesig dargestellt (vermulihc Originalmaße). Dieses sollte auf vernüftige Maße verkleinert werden (z.b. so wie auf Profilkachel). Damit wird das Profilformular gleich um einiges kompakter. 

Als zweiter Schritt wäre es super, wenn jeder Nutzer so wie bei Artikeln beliebig große Dateien hochladen kann, und wir die selbst runterskalieren. D.h., wir speichern auch nicht die riesig große Datei selber ab, sondern die runterskalierte, um Serverplatz zu schonen.

**Comment by marcaltmann** [comment]
Punkt 1 habe ich gerade gemacht, zu Punkt 2 kann ich nicht so viel sagen, aber ich denke zuerst brauchen wir dafür einen Überblick, wie viel Platz durch Profilbilder belegt wird. Zumindest haben wir aktuell wohl eine 2-MB-Grenze für Profilbilder.
