### ISSUE TITLE
Profil Box umbenennen

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1282]
https://www.fairmondo.de/user/edit

Die Box Profil sollte heißen Über mich. Dann kann auch der Titeltext in der Box über mich entfallen.

Die Box könnte in der Höhe vielleicht um ein Drittel reduziert werden, damit das Formular kompakter wird.

Als default Text in der Box, wenn sie leer ist, könnte stehen "Hier kannst Du Dich anderen Nutzer*innen vorstellen. Dein Text erscheint öffentlich in Deinem Profil. " Sollte natürlich nicht als Profiltext der Person gespeichert werden, nur als HInweis, was da rein kommt.

**Comment by marcaltmann** [comment]
Den Begleittext als Placeholder zu implementieren ist zu aufwändig. Wir platzieren ihn stattdessen oberhalb des Textfeldes.

**Comment by annakress** [comment]
OK
