### ISSUE TITLE
Profile anderer Nutzer / Rechtliches & Impressum

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1288]
Beispiel: https://www.fairmondo.de/users/ecobookstore/profile

Sieht recht häßlich aus, haben wir nie vernüftig gesetzt und strukturiert.

1) Ich würde auf jeden Fall alle Felder ausblenden, die jemand im Profil nicht befüllt, z.B. Fax und Tel.nr. Mobil hat Ecobookstore nicht, werden trotzdem eingeblendet.

2) Es wäre zu überlegen, ob man den Kasten um den ganzen Text nicht einfach weglässt.

3) Die einzelnen Abschnitte, z.B. Ansprechperson, AGB, etc. könnte man sicher besser abtrennen, eventuell durch klassische Trennlinie oder schöner formattierte Überschriften.

4) Ich schlage vor, den ersten Teil Ansprechperson komplett wegzulassen (ist für uns eher intern interessant), dafür Impressum & Kontakt ganz hoch zu ziehen, da stehen für den Kunden relevante Infos ja eh drin. Genauso könnte man den Nutzernamen ganz oben weglassen. Die Nutzerkachel ist ja sowieso darüber, also Ecobookstore muss da nicht in groß ganz oben stehen.

5) Die Überschriftsgrößen wären zu überprüfen, manche Dinge doppeln sich in der Größe, z.b. 
AGB und Allgemeine Verkaufsbedingungen des Fairmondo-Shops Ecobookstore
-> beide sind in gleicher Schriftgröße gesetzt, warum?

**Comment by chiramiso** [comment]
zu Punkt 5: Die Felder für AGB und so erlauben HTML Tags, wenn der*die Nutzer*in dies nutzt um zB Überschriften zu setzen, beißt sich das halt manchmal mit unseren Überschriften… das lässt sich aber auch schwer abstellen…


den Rest hab ich erstmal umgestellt
