### ISSUE TITLE
Nutzer kann Passwort nicht zurücksetzen

### ISSUE THREAD

**Issue by marcaltmann** [fairmondo/fairmondo#1289]
Aus dem OTRS:
"Thema: Technik und Datenschutz Inhalt: Hallo liebes Fairmondo-Team, leider schaffe ich es nicht mein Passwort zurückzusetzen. Ich habe es nun schon mehrfach versucht. Ich bekomme zwar die Passwort-Vergessen-Mail, wenn ich dann aber den Link anwähle und ein neues Passwort eingebe und es bestätige, wird dieser Bildschirm nochmals leer aufgerufen und das neue Passwort ist weg. Ich kann mich leider nicht mit dem neuen Passwort einloggen. Könnt Ihr mir helfen, mein Passwort zurückzusetzen? Eine neue Registrierung ist mit der Mail-Adresse nicht möglich."

**Comment by chiramiso** [comment]
Kann das irgendjemand nachvollziehen? Ich kann nicht nachstellen, weder lokal noch auf Staging, noch auf Production.

Einziges 'Problem' was ich mit einem Nutzer mal nachvollziehen konnte, der so eine Anfrage im OTRS stellte war, dass er vergessen hatte seine E-Mail Adresse zu verifizieren. Dann kann er auch sein Passwort nicht ändern oder sich einloggen.

**Comment by chiramiso** [comment]
Hab das Problem gefunden; passiert wenn die standard_address des users kaputt ist.

**Comment by chiramiso** [comment]
sollte jetzt funktionieren
