### ISSUE TITLE
CFK Billboard oder seitliche Grafik

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1297]
Details bitte mit Merlind absprechen.

**Comment by annakress** [comment]
die grafik  habe ich gerade an unsere mailingliste geschickt. die kommt überallhin wo bisher die kleine büchergrafik war (z.B. auf allen produktseiten). die büchergrafik entfällt dafür. die cfk-grafik soll über die geno-grafik (die büchergrafik war darunter platziert).

**Comment by marcaltmann** [comment]
Ich habe die Änderungen auf dem Branch feature-subscription umgesetzt. Der Link fehlt noch und natürlich das Billboard. Wenn alles fertig ist (am Montag), mache ich einen Pull Request dafür.

**Comment by annakress** [comment]
billboard wird noch von merlind entworfen. eventuell heute fertig.

**Comment by marcaltmann** [comment]
Billboard schaffe ich heute nicht mehr, bzw. erst heute Abend oder morgen früh.
