### ISSUE TITLE
Dem Nutzer Einkaufs-Impact anzeigen

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1302]

**Comment by annakress** [comment]
Der Nutzer soll auf einen Blick sehen, wieviel Faires Prozent durch seinen Einkauf gesammelt wurde und dementsprechend an Transparency geht.

Nach dem Abschluss des Verkaufs auf der Webseite und in der Käuferemail soll folgendes angezeigt werden:

Wie gehabt Vielen Dank für Deinen Einkauf. Dann den Zusatz: 

"Damit hast Du Fairmondo eine Spende von X Euro an Transparency International e.V. zur Bekämpfung von Korruption ermöglicht. 

Du möchtest mehr tun? Entdecke Deine Möglichkeiten, uns beim Aufbau eines fairen Unternehmen zu unterstützen. Link: http://mitmachen.fairmondo.de/aktiv-mithelfen/

(wobei ich den zweiten Absatz aus der Email rauslassen würde, damit sie kompakt bleibt)

X Euro wäre eben das Faire Prozent erzeugt durch den Kauf. Dazu Anmerkung von Paul: "Die Gesamtspende kann man ja auch direkt auf dem Nutzer speichern, oder man legt ein neues Model dafür an, in dem der Wert gespeichert wird, dann ists weder ein Problem, wenn die gekauften Artikel irgendwann gelöscht werden, noch hat man dann große Datenbanklast."

Achtung, da demnächst die Gebühr für Privatverkäufer entfällt, soll der Zusatz natürlich nur bei Artikel mit fairem Prozent angezeigt werden.

Ausbaustufe 2: Im Profil eine Aufsummierung aller ermöglichten Spenden anzeigen (noch zu konzipieren, wo)

Ausbaustufe 3: Gamification-Elemente (noch zu konzipieren)

**Comment by KonstantinKo** [comment]
Ausbaustufe 1 ist grundsätzlich fertig.
Was hauptsächlich noch fehlt sind Tests dafür. Komischerweise bekomm ich schon ohne Veränderungen auf dem develop branch hunderte Testfehler die wohl mit Emails zu tun haben ... Hab noch nicht rausgefunden woran das liegt.

Was auch noch nicht getan ist, ist Verhinderung des Aufrechnens durch gebührenlose Privatverkäufe und Nichtanzeige bei 0%.

**Comment by annakress** [comment]
Gebührenlose Pr.verkäufe gibt es vorauss. ab Mo live, also bitte mit berücksichtigen.
