### ISSUE TITLE
Falsche Email bei Anforderung neuer Registrierungsemail

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1307]
Fordere ich die Registrierungsemail an, weil ich sie nicht erhalten habe (also LInk im Hauptmenü unter Anmelden -> Reg.email nicht erhalten) erhalte ich statt der Reg.email die Email: 

Du hast Deine Emailadresse geändert

Hallo testnutzerin2,

Jemand hat Deine E-Mail-Adresse auf Fairmondo geändert. Um die Änderung Deiner E-Mail-Adresse zu bestätigen, klicke bitte auf folgenden Link

Getestet nicht auf dem Live-Server, sondern auf der Version, die auf Staging gerade steht. Wobei wenn ich auf den Link klicke, der schon das richtige tut, nämlcih meinen Account bestätigen.

---
Ausserdem: wenn ich den Reg.link eigentlich schon betätigt habe, und dann trotzdem (z.B. weil ich es vergessen habe) die Reg.email noch einmal anfordere, kommt gar nichts. KAnn man da nicht einfach noch mal die Reg.email zuschicken, auch wenn der Nutzer schon bestätigt ist, also macht es was, wenn er noch mal klickt? Oder gibt es damit ein Problem? Gar nichts zu bekommen ist schon verwirrend.

**Comment by chiramiso** [comment]
Genaugenommen ist das kein Bug und es wird genau die E-Mail versendet, die versendet werden soll. Es wird halt nicht unterschieden, ob eine neue E-Mail oder ein neuer Account bestätigt werden soll. Man könnte den Text in der E-Mail dementsprechend anpassen. Für Vorschläge bin ich offen.

Das keine E-Mail versendet wird, wenn der Account schon bestätigt ist, ist auch normales Verhalten (aus technischer Sicht) es gibt halt nur eine E-Mail wenn es einen unbestätigten Token gibt.

**Comment by annakress** [comment]
So ganz verstehe ich das nicht, da man ja durchaus wenn man sich neu registriert, eine andere Email bekommt (nämlich korrekt mit Willkommen und Registrierung bestätigen), in der man seine Registrierung bestätigen soll. Klicke ich aber auf Registrierungsmail noch mal anfordern, kommt ne andere... Am liebsten wäre mir, dass die richtige Mail kommt. Falls es aus irgendwelchen technischen Gründen superkompliziert ist, und wir einen quick fix machen, unten ein Änderungsvorschlag.

Betreff: [Fairmondo] Bitte bestätige Deine Emailadresse

Hallo testnutzerin2,

Du hast Dich entweder neu auf dem Marktplatz registriert, oder Deine Emailadresse geändert. Wir bitten Dich deshalb, Deine Emailadresse zu bestätigen. Klicke dazu auf folgenden Link:

Emailadresse bestätigen

Falls Du diese E-Mail nicht angefordert hast, wende Dich bitte an unseren Kundenservice: kundenservice@fairmondo.de oder ignoriere einfach diese E-Mail.

Dein Fairmondo-Team

**Comment by chiramiso** [comment]
Aus technischen Gründen ist es leider super kompliziert. Ich werde den Text ändern.
