### ISSUE TITLE
Verkaufsformular Scrollverhalten

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1311]
Wenn ich mich durch die Boxen im Verkaufsfomular klicke, scrollt das Formular manchmal ungünstig nach oben, also damit auch die Box teilweise aus dem Sichtfeld. Eine sich öffnende Box sollte oben einrasten, und nicht ausser sichtweite scrollen.

**Comment by marcaltmann** [comment]
Fixed.
