### ISSUE TITLE
Vorlage übernehmen / Vorauswahl

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1313]
Wenn ich über mein Profil unter Meine Vorlagen eine Vorlage über Vorlage übernehmen auswähle, komme ich auf das Verkaufsformular. Sinnvoll wäre dann, wenn die Vorlage schon ausgewählt wäre, stattdessen muss ich im Formular wieder in der Dropdown Box die Vorlage auswählen. Wobei die anderen Felder des Formulars korrekt von der Vorlage übernommen werden....

**Comment by 01-Scripts** [comment]
Evtl. passend zum Thema:
Wenn ich in der Vorlage Bilder mit abgespeichert habe werden mir diese ja direkt mit angezeigt. Ich kann nicht passende Bilder dann zwar löschen aber nicht direkt mit einem anderen Bild ersetzen. Ich muss also erst die Bilder löschen, dann die Artikelvorschau aufrufen und dann nochmal bearbeiten um dann wieder die richtigen Bilder hochladen zu können.

**Comment by chiramiso** [comment]
Done und online
Kommentar in eigenes Issue ausgelagert (#1362)
