### ISSUE TITLE
Vorlage speichern

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1314]
WEnn ich im Verkaufsformular eine Vorlage speichern will, muss ich dazu das Häckchen setzen und den Vorlagennamen eintragen. Etwas einfacher wäre es, wenn ich das Häckchen gar nicht erst setzen muss, also diese Zeile komplett entfällt. Also wenn ich einen Namen in das Feld eingetragen habe, heißt das auch automatisch, dass ich die Vorlage speichern will.

**Comment by chiramiso** [comment]
Done.
