### ISSUE TITLE
Artikel bearbeiten

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1315]
Will ich einen Artikel bearbeiten, klicke ich auf "Artikel bearbeiten oder löschen". 

Deiser Link nimmt den Artikel ja vom Marktplatz. Danach muss ich aber noch ein zweites Mal entweder auf Bearbeiten und Wiedereinstellen oder auf Löschen klicken. Ich erinnere mich, dass wir das lange diskutiert hatten. Aber gibt es inzwischen vielleicht doch die Möglichkeit, Shortcuts einzubauen?

Mein Wunsch wäre: Ich will einen Artikel bearbeiten und gehe dazu auf den Artikel. Dann sehe ich 3 Links: 

Bearbeiten -> führt direkt auf das editierbare Verkaufsformular. Im Hintergrund wird der Artikel halt automatisch vom Marktplatz genommen.
Löschen -> eben löschen mit Rückfrage, ob gelöscht werden soll
Vom Marktplatz nehmen -> wie gehabt

Falls das weiterhin ein großes Problem ist, bitte zumindest den Link "Bearbeiten und wiedereinstellen" im zweiten Schritt einfach in Bearbeiten ändern.

**Comment by chiramiso** [comment]
![image](https://cloud.githubusercontent.com/assets/4174002/6143722/7fd50d7e-b1cd-11e4-844c-046dec7d29f5.png)

**Comment by chiramiso** [comment]
![edit_buttons](https://cloud.githubusercontent.com/assets/4174002/6143726/9b005018-b1cd-11e4-8056-446f1d38c1e4.jpeg)

**Comment by chiramiso** [comment]
![hhsul](https://cloud.githubusercontent.com/assets/4174002/6143738/e20e77c8-b1cd-11e4-96e2-fc551aa9d62c.jpg)

**Comment by chiramiso** [comment]
Nee, mal im ernst, schon machbar, will aber gut getestet sein, weil irgendwie mehr magie im hintergrund als ich dachte. wird daher diese woche nicht mehr mit gutem gewissen online gehen.

**Comment by marcaltmann** [comment]
:-)

**Comment by annakress** [comment]
eine runde sache!

**Comment by chiramiso** [comment]
Done
