### ISSUE TITLE
Autocomplete "off" für login form

### ISSUE THREAD

**Issue by andreasknoepfle** [fairmondo/fairmondo#1316]
In 976f6dc7adc689d4cf97fb74ea278c2df2cb3ca8 musste ich kurzfristig das native autocomplete für das email-eingabefeld in unserem login ausschalten da in den meisten browsern das dropdown zuklappt wenn man in die autocomplete-box mit dem mauszeiger fährt.

Da es für E-Mailadressen ganz praktisch ist und sich das Browser autocomplete schlecht steuern lässt schlage ich vor bei erfolgreichem login ein cookie zu setzen das die eMail Adresse speichert ( dann sind auch keine Tippfehler drin) und diese beim nächsten login durch den cookie wieder mit einem jquery autocomplete (oder ähnliches) anzuzeigen.

**Comment by marcaltmann** [comment]
Danke für den Quickfix, aber der scheint bei mir nichts zu bringen. Problem besteht bei mir immer noch (Firefox, Chrome unter Linux).
Ich würde ehrlich gesagt ungern eine Browser-Funktionalität wie Formular-Autocomplete nachbauen, auch wenn sie gut umgesetzt ist. Bin eher dafür, die Dinge so einfach wie möglich zu halten.
Vermutlich lässt sich der Fehler beheben, wenn wir nicht über CSS :hover gehen, sondern es mit JavaScript machen, in Kombination mit den native mouseout-Events. Ich gehe dem mal nach.
Ansonsten können wir auch wieder zur Klick-Lösung zurückkehren.

**Comment by andreasknoepfle** [comment]
google macht übrigens etwas ähnliches. Zwar kein autocomplete aber ein account der einmal eingeloggt ist wird im cookie gespeichert und beim login aufgeführt. 
Warum sollte man nicht eine native browser funktion ändern, wenn sie nicht richtig in jedem browser umgesetzt ist uns zudem noch nachteile bietet ( zB werden auch falscheingaben und tippfehler ins autocomplete aufgenommen) 
Kann es vlt sein das der quick fix bei dir nocht funktioniert weil ich ihn nur im master branch und auf production eingestellt habe ? autocomplete="off" sollte doch von jedem browser unterstützt werden, sonst wären jquery autocompletes nicht möglich.

**Comment by marcaltmann** [comment]
Der Quickfix funktioniert bei mir in Firefox tatsächlich nicht, in Chrome schon (auf Production). Ich finde das mit den Cookies schon interessant, vor allem wie Google das umgesetzt hat. Aber ich persönlich würde mir gut überlegen, neue Features einzuführen. Dadurch, dass jetzt erstmal ein Bug gefixed werden muss, fühle ich mich da auch etwas unter Druck.

**Comment by marcaltmann** [comment]
Ich hab jetzt mal auf Staging nen Fix deployed zum Testen.
