### ISSUE TITLE
Andere Nutzer leichter kontaktieren

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1317]
Wenn man auf einen Artikel geht, kann man über die Box rechts eine Email an den Anbieter versenden. DIe gleiche Box sollte sich im Profil des Anbieters finden.

Also auf fairmondo.de/users/username -> Unter den ganzen Boxen Sammlungen, AGB usw. eine neue Box. Diese sollte "Email an den*die Anbieter*in" heißen. Verhalten genau wie die Box in der Artikelansicht.

**Comment by chiramiso** [comment]
Ach verdammt, jetzt versteh ich was Du mit Boxen meinst. Jetzt hab ich was gebaut, was an einer ganz anderen Stelle ist.
Ähm, nagut. Wie wärs denn mit einem Overlay, ähnlich dem zum Warenkorb als E-Mail verschicken. Ich glaub ich mach das so, eine Ausklapp-Box an der Stelle, die Dir da vorschwebt macht wenig Sinn.

**Comment by chiramiso** [comment]
fertig
