### ISSUE TITLE
Besseres Onboarding Neue Verkäufer

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1318]
In der Hauptnavi gibt es den Link Verkaufen. Wenn ich nicht eingeloggt bin, führt er auf die Anmelde/Registrierseite.

In Zukunft soll dort aber eine Info-Seite für Verkäufer entstehen, die eben anders ist als die generische Anmelde/Registrierseite.

Könntet Ihr bitte eine Kopie der Anmelde/Registrierseite anlegen, auf die automatisch geleitet wird, wenn ich nicht eingeloggt bin und auf Verkaufen klicke? Auf dieser Kopie wird oberhalb und unterhalb der Anmelde/Registriermasken noch weitere Text erscheinen, der nur für Verkäufer relevant ist (Texte bereite ich heute und morgen vor).

**Comment by annakress** [comment]
Mockup landing page unter menüpunkt "Verkaufen".
Mir wäre es wichtig, dass wir überhaupt dort Texte platzieren. Falls ein sinnvolles Styling bis Mi nicht möglich ist, reicht es mir auch, wenn ich da einen CMS-Text selbst einfügen kann.

![verkaufenlandingpage 1](https://cloud.githubusercontent.com/assets/2988567/6080891/67f89dda-ae15-11e4-929a-ceff2c466271.png)

**Comment by annakress** [comment]
Und hier die Texte Copy&Paste:


Fairmondo - die faire Alternative zu den Marktriesen im Online-Handel

- Verkaufe neue oder gebrauchte Artikel - ohne Einschränkungen
- Komplett kostenfrei wenn Du privat verkaufst
- Wir schützen Deine Daten und Privatsphäre
- Gemeinsam bringen wir Fairness und Transparenz in den Online-Handel

Du kaufst und verkaufst privat

Deine Vorteile:

- Kaufen, verkaufen, leihen oder tauschen - alles komplett kostenfrei
- Profi-Funktionen wie Versandrabattregeln oder eingebettete Videos Deiner Artikel
- Sammle ganz einfach Spenden für Dein Lieblings-Hilfsprojekt 
- Gemeinsam erschaffen wir ein Unternehmen, das vielen gehört und ohne große Investoren auskommt

Du kaufst und verkaufst gewerblich

Deine Vorteile:

- Keine Einstellgebühr
- Nur 4% Verkaufsgebühr für fair gehandelte Artikel, und 7% für alle anderen Artikel
- Profi-Funktionen wie Versandrabattregeln oder CSV-Schnittstellen
- Demokratische Kontrolle des Unternehmens durch Dich als Genossenschaftsmitglied (https://www.fairmondo.de/genossenschaft/)

                                                       Du hast noch Fragen?

- Schau in unsere FAQ für Verkäufer*innen (https://www.fairmondo.de/faq#d1)
- Triff andere Verkäufer*innen in unserem Forum (https://forum.fairmondo.de/c/verkaufer-innen-forum)
- Frage unseren freundlichen Kundenservice (https://www.fairmondo.de/feedbacks/new?variety=get_help)

**Comment by annakress** [comment]
da die texte einen verweis auf privatverkäufer-ohne-gebühren enthalten - sollte natürlich erst online, wenn wir die version auch online bringen.

**Comment by annakress** [comment]
Nachtrag: das es doch noch nicht möglich ist mit den Videos, müßte der Text heißen statt:

Profi-Funktionen wie Versandrabattregeln oder eingebettete Videos Deiner Artikel

-> Profi-Funktionen wie Versandrabattregeln

**Comment by chiramiso** [comment]
Äh, ich seh da im Text den Hinweis, dass die Gebühren für Verkäufer 4% bzw 7% betragen. Ist das jetzt so? Wann soll das umgesetzt sein? Das passiert ja nicht einfach so, nur weils in nem Text steht...

**Comment by annakress** [comment]
war doch schon immer so: https://www.fairmondo.de/faq#e1
