### ISSUE TITLE
Community Menü vereinfachen

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1319]
Der Community Eintrag im Hauptmenü soll auf folgende Unterpunkte schrumpfen und ein wenig wird auch die Reihenfolge abgeändert (LInks wie gehabt):

    Forum

    Aktiv mithelfen - http://mitmachen.fairmondo.de/

    Veranstaltungen - http://mitmachen.fairmondo.de/veranstaltungen/

    Partnerprogramm - http://mitmachen.fairmondo.de/materialecke/partnerprogramm/ (wird später ein Link zum Affiliate Programm)

    Genossenschaft - https://www.fairmondo.de/genossenschaft/

**Comment by marcaltmann** [comment]
Fehlt jetzt nicht der Forumslink?

**Comment by annakress** [comment]
ist wie gehabt.

**Comment by marcaltmann** [comment]
Ich meinte, es gibt aktuell keinen Eintrag "Forum" im Menü. Soll es aber, oder?

**Comment by annakress** [comment]
ah, dann hat den jemand aus versehen entfernt. war vorher da. der link ist https://forum.fairmondo.de/
