### ISSUE TITLE
Suche Erweiterte Optionen und Ergebnisanzeige

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1331]
Suche ich z.B. mit der Einschränkung fairer Filter, oder z.B. PLZ, wird die Anzahl der Suchergebnisse in der vertikalen Suchergegnisleiste nicht reduziert, sondern zeigt z.b. weiter Bücher (1895276) an. Klicke ich aber auf Bücher (1895276), dann werden korrekt nur 2 Seiten faire Bücher angezeigt.

**Comment by andreasknoepfle** [comment]
das was wir  als filter in es angelegt haben sollten eigentlich queries sein (mit ausnahme vom kategoriefilter) dann sollte das wieder gehen
