### ISSUE TITLE
Profil: Angaben zu Versandrabatten werden nicht gespeichert

### ISSUE THREAD

**Issue by 01-Scripts** [fairmondo/fairmondo#1332]
Ich wollte gerade in meinem Profil Angaben zu Versandrabatten eingeben.
Ich habe dazu alle Felder ausgefüllt und abgespeichert.
Wenn ich danach mein Profil aber wieder aufrufe sind die Felder wieder leer. Es scheint es wurde nichts gespeichert.
Kann das jemand reproduzieren?
Browser: Opera 27.0.1689.69

**Comment by chiramiso** [comment]
Privates oder gewerbliches Konto?

**Comment by annakress** [comment]
Privat.

**Comment by chiramiso** [comment]
Okay, sollte gefixt sein.
