### ISSUE TITLE
Kategorien im Backend hinzufügen

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1333]
ich wollte im backend eine neue kategorie hinzfügen und kriege 500 fehler.

**Comment by annakress** [comment]
eventuell auch einfach im backend hinzufügen, neue kategorie: 

Medien > Games > PC/Mac > "RPG/Rollenspiel"

**Comment by KonstantinKo** [comment]
Hotfixed. Kategorien haben keine slugs generiert, das sollte jetzt behoben sein.

**Comment by KonstantinKo** [comment]
Hab jetzt auch die Kategorie bei Rails-admin eingegeben und es hat funktioniert. Man kann leider nicht ohne Konsole die Position in der Hierarchie bestimmen. Ich werd das mal ändern ...
