### ISSUE TITLE
Ecobookstore Billboard reaktivieren

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1337]
Ecobookstore bietet wieder versandkostenfreien Versand an, und das sollten wir bewerben. Wir können einfach das alte Billboard, das wir über Weihnachten hatten, wieder einschalten. Als zweites nach dem Abo-Billboard. Das wir haben sie alle Billboard sollte dann ans Ende der Slideshow wandern.

Achtung: Versandkostenfrei sind nur Bücher und Hörbücher, eventuell muss der Text angepasst werden. Der Verweis auf die Gutscheine sollte bleiben, die sind ja weiter da.

Vielen Dank!

**Comment by chiramiso** [comment]
Wenn nur Bücher und Hörbücher versandkostenfrei sind stimmt das mit den "2 Millionen Artikel versandkostenfrei" nicht, das ist Teil des Bildes

Der Verweis auf die Gutscheine ist Teil des Bildes und bezieht sich auf Weihnachten. Soll das wirklich so bleiben? Wenn nicht, müsste das Bild geändert werden.

**Comment by chiramiso** [comment]
done
