### ISSUE TITLE
Suche um Händlersuche erweitern

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1341]
![untitled](https://cloud.githubusercontent.com/assets/2988567/6255934/55fe3470-b7b4-11e4-8b06-21c42ee10fc3.png)
Nutzer sollen nach Händlern und ihren Artikeln suchen können.

Wie heute mit Andi besprochen:

Interface Suchleiste siehe Anhang. 

Wenn der Nutzer nichts in das Anbieter Feld einträgt, soll die Suche per Default über alle Anbieter gehen. 

Wenn der Nutzer einen Suchbegriff (z.B. Fahrrad) und den Anbieternamen angibt, werden nur Fahrräder von dem Anbieter angezeigt.

Wenn der Nutzer keinen Suchbegriff und nur den Anbieternamen eingibt: Dann werden alle Artikel dieses Anbieters angezeigt, aber über den Artikeln wird der String eingeblendet "Zum Profil von Nutzername" eben als Link aufs Profil.

**Comment by annakress** [comment]
schade, dass hier anscheinend noch nix passiert ist...

**Comment by marcaltmann** [comment]
Ich sehe zwei Schwierigkeiten mit diesem Issue:
1. Es ist nicht spezifiziert, was in schmaleren Ansichten (Tablet, Mobil) mit dem Feld passieren soll.
2. Wenn das Feld für die Händlersuche neben dem normalen Suchfeld platziert wird, bekommt die Händlersuche eine sehr große Bedeutung – sie steht dann auf einer Stufe mit dem normalen Suchbegriff. Und das ist m.E. ungerechtfertigt, weil die allermeisten Suchanfragen wohl ohne Händlersuche ablaufen werden.

Ich schlage vor, die Händlersuche stattdessen in die Filter aufzunehmen, z.B. zwischen Preis und Standort. Dazu können wir die Filter entweder etwas schmaler machen bzw. anders anordnen oder das "Sortieren"-Element herausnehmen (und es rechts oberhalb des Filters positionieren, ähnlich wie bei Amazon).

**Comment by annakress** [comment]
zu 2: das ist strategisch so gewollt, damit wir in richtung vision von farimondo als einem nutzerzentrierten marktplatz gehen. also bitte nicht in filtern verstecken. sollte das feature gar nicht von den nutzern angenommen werden, kann man drüber nachdenken. zudem ist das feature wichtig für die gutscheine, die händlergebunden sind.
zu 1: da müsst ihr eben eine lösung finden. im ersten schritt, auch wenn nicht besonders kreativ, könnte man das feld mobil nicht anzeigen, wäre aber schade wegen 1.

**Comment by marcaltmann** [comment]
Some more ideas have been discussed to make searching for vendors possible. It would be nice if there was only one input field in the search bar. The search would then return both articles and vendors found with the particular search string. Results would be shown in the autocomplete window and on the search results page.

**Comment by marcaltmann** [comment]
Search by seller now works in the regular search field.
