### ISSUE TITLE
GWÖ Bilanz

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1342]
wir sind frisch gwö-bilanziert, und wollen das auf dem marktplatz zeigen. dazu solll unten im footer links unterhalb der social meida icons diese grafik kommen: http://www.spielscheune-der-geschichten.de/typo3temp/pics/3b26a9e084.png

die grafik linkt auf https://www.fairmondo.de/contents/gwoe-bilanz

leider hab ich es nicht geschafft, auf der seite eine grafik und ein pdf zu verlinken, diese müssen vermutlich von euch auf den server gebracht werden? Ich schicke beide an unsere mailingliste und ihr gebt mir einfach den pfad... danke!

wir können die gwöbillanz ganz gut für die kommunikation gebrauchen, ist also auch cfk-relevant.

**Comment by annakress** [comment]
grafik und pdf habe ich erledigt, hab sie einfach auf den blog hochgeladen und dann verlinkt. die seite ist also fertig zum verlinken über die grafik auf der startseite.

**Comment by marcaltmann** [comment]
Habe es gerade als PR eingestellt.
Die Responsiveness der Bilanzgrafik konnte ich auch herstellen, es ist nicht die schönste Lösung, funktioniert aber.

**Comment by annakress** [comment]
super, danke!
