### ISSUE TITLE
Schrift für Überschriften auf der Startseite

### ISSUE THREAD

**Issue by marcaltmann** [fairmondo/fairmondo#1343]
Die Überschriften auf der Startseite sind aktuell als Großbuchstaben in normaler Stärke gesetzt. Dadurch sind sie schlecht lesbar und sehen auch nicht gerade attraktiv aus. Eine einfache und wirkungsvolle Möglichkeit zur Verbesserung ist, sie einfach in Fettschrift zu setzen (siehe Screenshot).

![ueberschriften-startseite](https://cloud.githubusercontent.com/assets/2727647/6277147/882da808-b88c-11e4-9410-272bf777a6dc.png)

**Comment by annakress** [comment]
ist auf jeden fall besser, als grossbuchstaben.
