### ISSUE TITLE
Verkaufsformular Kategorienübersicht

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1349]
im verkaufsformular sieht man im abschnitt artikelbezeichnung und kategorien gar nicht, welche kategorien es gibt, erst, wenn man anfängt, diese auszuwählen.

Für eine bessere Usability soll der Link platziert werden: https://www.fairmondo.de/categories/

Man könnte z.B. unter dem Kategorienfeld einen Text mit Link einfügen "Eine Übersicht aller Kategorien findest Du hier." Der Link sollte ein neues Tab öffnen, damit der Nutzer nicht das Formular durch einen Klick verliert.

**Comment by chiramiso** [comment]
Done
