### ISSUE TITLE
Faires Prozent Text leicht anpassen

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1360]
Das faire Prozent
    1% werden von uns an Transparency International gespendet

Dieser Spruch steht ja bei jedem Angebot und zwar unter dem Artikelbild und damit in unmittelbarem Bezug zum Anbieter.

Wäre es kurzfristig möglich den Text in "1% werden von Fairmondo an Transparency International gespendet" zu ändern ?

Wenn ich nämlich als "Mitbewerber" z.B. den Markus ( @Ecobookstore ) fragen würde, ob er mir nachweisen kann, daß er auch wirklich die 1% abführt, dürfte ihm das schwerfallen. wink

Aber für mich steht dieses "uns" eindeutig in Bezug auf den Anbieter, weil der angebotene Artikel steht ja nicht in Bezug zu Fairmondo selber.

**Comment by chiramiso** [comment]
consider it done.
