### ISSUE TITLE
Blauer Kasten Startseite

### ISSUE THREAD

**Issue by annakress** [fairmondo/fairmondo#1361]
der text auf der startseite in dem obigen blauen kasten ist nicht mehr korrekt. ich schlage vor:

Das macht uns anders:

Die schönsten und fairsten Produkte im Netz ent­decken

Kostenfrei für private Verkäufer*innen

Nur 6% Verkaufs­provision (3% für faire Artikel)

Ein faires Unternehmen dahinter

**Comment by marcaltmann** [comment]
Fixed.
