### ISSUE TITLE
Artikel/Transaktionen als bezahlt markieren können

### ISSUE THREAD

**Issue by marcaltmann** [fairmondo/fairmondo#1365]
Es ist aus der Liste der Einkäufe (Profil > Deine Einkäufe) nicht ersichtlich, welche Einkäufe bereits bezahlt sind.
- Man sollte zunächst, wenn verschiedene Zahlungsmethoden für einen Einkauf verwendet wurden, für jede Methode einzeln festlegen können, ob bezahlt wurde.
- Wenn PayPal als Zahlungsmethode verwendet wurde, sollte die Markierung automatisch nach der PayPal-Transaktion erfolgen.
- Für einen höheren Komfort sollte man auch einen ganzen Einkauf als bezahlt markieren können (PayPal ausgenommen), evtl. direkt aus der Liste "Deine Einkäufe".
- In der Liste "Deine Einkäufe" sollte man schnell sehen können, welche Einkäufe bezahlt/zum Teil bezahlt oder noch gar nicht bezahlt sind.

**Comment by annakress** [comment]
noch wichtiger ist der workflow für gewerbliche händler, den müsste man sich mal anschauen.

**Comment by 01-Scripts** [comment]
Dann wäre es auch noch nett wenn man als Verkäufer Artikel/Bestellungen mit einem Klick als verschickt markieren könnte.

**Comment by hesslau** [comment]
der Bezahlungsstatus sollte auch im Checkout-Prozess angezeigt werden. Derzeit wird der "Bezahlen über Paypal" Button angezeigt, auch wenn das Produkt bereits bezahlt wurde. Dafür kann der Status im transaction object genutzt werden
