### ISSUE TITLE
PayPal-Account heißt noch "Fairnopoly eG"

### ISSUE THREAD

**Issue by marcaltmann** [fairmondo/fairmondo#1370]
Bei PayPal-Zahlungen zahlt man immer noch an die "Fairnopoly eG", nicht an "Fairmondo eG" (siehe Screenshot). Laut Kundenbetreuung irritiert das die Kunden.
![bildschirmfoto-paypal](https://cloud.githubusercontent.com/assets/2727647/6596732/5a2ddbce-c7f7-11e4-9878-3c0621df6d58.png)

**Comment by annakress** [comment]
habs geändert, bitte überprüfen.

**Comment by marcaltmann** [comment]
Gibt es eine Möglichkeit, das zu überprüfen, ohne etwas zu kaufen?

**Comment by marcaltmann** [comment]
Fixed
