### ISSUE TITLE
CSV Schnittstelle Datei ist nicht verlinkt

### ISSUE THREAD

**Issue by Merlind** [fairmondo/fairmondo#1374]
Auf der FAQ Seite funktioniert der Link zur CSV Schnittstelle nicht.
![bildschirmfoto 2015-03-16 um 09 58 17](https://cloud.githubusercontent.com/assets/7868669/6663074/36274236-cbc3-11e4-8956-059652b322ac.png)

**Comment by chiramiso** [comment]
Doch, der Link funktioniert, du musst nur als gewerbl Nutzer angemeldet sein…

**Comment by annakress** [comment]
man wird ja korrekt auf die anmelde-seite weitergeleitet. schlage trotzdem vor in der faq dazuzuschreiben z.b. in klammern "(nur für angemeldete gewerbliche Nutzer*innen)"

**Comment by chiramiso** [comment]
Habs in den FAQs geändert
