### ISSUE TITLE
Händler kann sich nicht einloggen

### ISSUE THREAD

**Issue by Merlind** [fairmondo/fairmondo#1380]
Mich hat folgende Mail eines Händlers erreicht. Er ist einer der Händler des Überraschungsabos und er wollte die Produkte jetzt einstellen, da die Abonnenten evtl. die Produkte nachbestellen wollen.

Hallo Merlind,

ich wollte heute die Produkte bei fairmondo einstellen, leider hat der Login nicht funktioniert. 

Normalerweise hat es mit info@koawach.de + Passwort geklappt.

Unter "Passwort vergessen" ist leider keine Email gekommen.

Habe ich etwas falsch gemacht? Wo liegt der Fehler?

Belebende Grüße
Heiko von koawach

**Comment by andreasknoepfle** [comment]
Die email war butz@koawach.de

**Comment by 01-Scripts** [comment]
Es ist glaube ich nicht ganz so geschickt die E-Mail-Adresse von Kunden hier öffentlich in den Bugtracer zu stellen.

**Comment by annakress** [comment]
Hab ich entfernt, Du hast vollkommen recht. Bitte keine Personendaten hier.
