### ISSUE TITLE
Sammlungen überarbeiten

### ISSUE THREAD

**Issue by marcaltmann** [fairmondo/fairmondo#1383]
Die Sammlungen sollen verschönert und das Design vereinfacht werden. Die Artikelfotos sollen stärker in den Vordergrund treten.

- Sammlungsübersichten überarbeiten
- Einzelansichten verbessern, Ersteller der Sammlung besser herausstellen
- Passende Sammlungen für Kategorien anzeigen, wenn kein Suchbegriff angegeben wurde

**Comment by marcaltmann** [comment]
Update:
Habe mich mit Merlind zusammengesetzt und ihr eine Überarbeitung der Sammlungsübersichten gezeigt (größere Bilder, nur zwei statt drei Sammlungen in einer Zeile, siehe Screenshot). Sie fand sie gut. Bei den Kommentaren fanden wir beide es besser, zunächst auf sie zu verzichten, u.a. weil es unüberichtlicher wäre und die Sammlungsboxen dadurch unterschiedlich hoch würden, was auf der Seite nicht so schön aussehen würde.

Bei den Einzelansichten für die Sammlungen gibt es noch ein paar Probleme. Wir suchen im Moment nach einer Lösung, die Informationen über den Ersteller der Sammlung platzsparend am Anfang der Seite zu platzieren.

![sammlungen](https://cloud.githubusercontent.com/assets/2727647/7072074/eb319c06-dee9-11e4-8a64-3560b87b89ff.png)

**Comment by 01-Scripts** [comment]
Das neue Layout sieht ansprechend aus.
Eventuell könnte in dem Zug auch die "Kein Bild"-Grafik schöner gestaltet werden?
