### ISSUE TITLE
Personalisierte Navileiste

### ISSUE THREAD

**Issue by marcaltmann** [fairmondo/fairmondo#1386]
Wurde im Forum angefragt und ist ja auch ein sinnvolles und leicht umzusetzendes Feature: Oben rechts in der Navileiste den Nutzernamen anzeigen, wenn man angemeldet ist, z.B.:

Verkaufen | Sammlungen | Community | username | Warenkorb

Im Dropdown-Menü von username dann z.B. folgende Menüpunkte:

- Mein Profil
- Meine Sammlungen
- Logout

**Comment by chiramiso** [comment]
Einmal mit Christian zusammensetzen bitte, der arbeitet grad an nem Konzept für die Navileiste
