### ISSUE TITLE
Darstellungsproblem (Leerstelle in Libraries)

### ISSUE THREAD

**Issue by 01-Scripts** [fairmondo/fairmondo#1389]
z.B.: https://www.fairmondo.de/libraries/7879
![image](https://cloud.githubusercontent.com/assets/200336/7144984/6321280a-e2e9-11e4-808d-4c589e15a733.png)

Browser: Opera 28

**Comment by marcaltmann** [comment]
Die Leerstelle hat nichts mit dem Artikel darüber zu tun, die ist aus einem anderen Grund leer, den ich im Moment nicht erkennen kann.

**Comment by 01-Scripts** [comment]
OK. Danke für die Info. Ich hab den Titel des Issues dann mal angepasst.

**Comment by marcaltmann** [comment]
Danke.

**Comment by marcaltmann** [comment]
Bei dieser Sammlung gibt es das Problem auch:
https://www.fairmondo.de/libraries/7351

![thokkthokk](https://cloud.githubusercontent.com/assets/2727647/7201394/c215f416-e506-11e4-86e4-719289f7848f.png)

**Comment by 01-Scripts** [comment]
Der Code scheint leere Grid-items zu erstellen. Hat der Anbieter vielleicht einzelne Angebote deaktiviert o.ä.?
![image](https://cloud.githubusercontent.com/assets/200336/7215205/59e54b8c-e5cc-11e4-8236-19fae6f85875.png)

**Comment by chiramiso** [comment]
allet jut
