### ISSUE TITLE
Startseite Logos für Spendenpartner Images fehlen

### ISSUE THREAD

**Issue by Merlind** [fairmondo/fairmondo#1393]
siehe Betreff

![bildschirmfoto 2015-04-20 um 15 11 17](https://cloud.githubusercontent.com/assets/7868669/7230580/851a3f2a-e76f-11e4-89ee-12ebffe689c4.png)

**Comment by chiramiso** [comment]
Gab neue Styles für Userbilder, die vom System erst bearbeitet werden mussten. Sobald der Worker durch ist, sind alle Userbilder wieder da…
