### ISSUE TITLE
Profilbilder falsch/vertauscht?

### ISSUE THREAD

**Issue by mi2ma** [fairmondo/fairmondo#1406]
Hallo allerseits,
habe mich gerade angemeldet und fest gestellt, dass mein Profilbild nicht mich zeigt (könnte wohl Olli sein). Ich hatte ein Bild drinnen, es scheint somit irgendwie vertauscht worden zu sein.

Grüße!
Michael

**Comment by marcaltmann** [comment]
Wie lautet denn der Nutzername?

**Comment by mi2ma** [comment]
held-von-kosmos

**Comment by marcaltmann** [comment]
Hallo Michael,
leider können wir das nicht von uns aus wieder richtig zuordnen. Bitte einfach das Profilbild löschen und nochmals einstellen.
Danke.

**Comment by mi2ma** [comment]
Hallo Marc,
klar, kein Problem.
Hauptsache es passiert nicht andauernd und die Nutzer erkennen sich selbst nicht mehr...
Grüße!
