### ISSUE TITLE
Falsche Anzahl von Artikeln beim ecobookstore

### ISSUE THREAD

**Issue by marcaltmann** [fairmondo/fairmondo#1414]
Z.B.: https://www.fairmondo.de/articles/memo-match-spiel-ean-9001890607790

Nutzer:
Die Anzahl muss mindesten 10 sein (außer es wurde etwas verkauft).
Könnt Ihr das bitte verifizieren und mal eine Selektion laufen lassen, die alle Artikel von uns mit einer Anzahl von 3 oder kleiner sucht. Abhängig von diesem Ergebnis können wir uns dann überlegen, wie wir das korrigiert bekommen.

**Comment by marcaltmann** [comment]
Code vom Mass-Uploader ansehen und auf Development testen, was passiert, wenn man den Wert für quantity_available direkt verändert.

**Comment by mjrk** [comment]
Der Fehler ist bereits durch einen Callback im ArticleObserver behoben. 

Allerdings wurde dieser Callback erst hinzugefügt,  nachdem einige Artikel bereits mit der neuen Anzahl importiert wurden. Da der Callback nur ausgeführt wird, wenn sich die Anzahl ändert, hatten weitere Importe keinen Effekt.
