### ISSUE TITLE
Fehler redirect Feedback zu Artikel an Fairmondo

### ISSUE THREAD

**Issue by Chimperoni** [fairmondo/fairmondo#1439]
bitte hier lesen

https://forum.fairmondo.de/t/404-bei-feedback-an-fairmondo/1204

**Comment by marcaltmann** [comment]
Hi @Chimperoni, danke für das Issue. Kannst du Issues in Zukunft bitte auf Englisch einstellen?

**Comment by Chimperoni** [comment]
Hallo @marcaltmann, gerne auf Englisch. Gilt das auch für die Beschreibung/Kommentare?

**Comment by marcaltmann** [comment]
@Chimperoni Ja, bitte für alles, was auf Github ist, wenn möglich. Ist besser, wenn jemand nicht so gut Deutsch spricht, wie einer unserer freiwilligen Programmierer gerade.
