### ISSUE TITLE
Drop condition Fair for Affiliate Program

### ISSUE THREAD

**Issue by annakress-bd** [fairmondo/fairmondo#1449]

**Comment by annakress-bd** [comment]
Sorry, I created the issue with a wrong account :-)

For Belboon, our affiliate program, we want to drop the condition Fair. That means all products of professional sellers should participate in the program, no matter what label is attached to the product.

**Comment by marcaltmann** [comment]
Fixed by 0931fc0e8bf4f17e897a16fd38a30013a550f5b2
